spring:
    application:
        name: Hospital-Management-System
    datasource:
      url: jdbc:mysql://localhost:3306/hospitalmanagementsystem
      username: root
      password: "${DB_PASSWORD}"
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
#    flyway:
#        enabled: true
#        locations: classpath:db/migrations

#debug: true 